version: '3'

services:
  influxdb:
    image: arm32v7/influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydatabase
      - INFLUXDB_USER=thinh
      - INFLUXDB_USER_PASSWORD=12345
    volumes:
      - ./influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.5.10
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=12345
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

